version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - /var/lib/postgresql/data
    ports:
      - '5432:5432'
  redis:
    image: redis:alpine
    command: redis-server
    volumes:
      - redis:/data
    ports:
      - 6379
    logging:
      driver: none
  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/opt/app
    depends_on:
      - redis
  whenever:
    build: .
    command: bash -c "bundle exec whenever --update-crontab"
    volumes:
      - .:/app
    depends_on:
      - app
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - '3000:3000'
    volumes:
      - .:/opt/app
      - rubygems:/usr/local/bundle
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: bash -c 'bin/setup && rails server -b 0.0.0.0 -p 3000'
volumes:
  rubygems:
  redis:
